# Generated by Django 5.0.6 on 2024-05-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('keywords', models.TextField(blank=True, null=True)),
                ('human_presence', models.CharField(blank=True, choices=[('M', 'Multiple'), ('S', 'Single'), ('-', 'None')], max_length=1, null=True)),
                ('visibility', models.CharField(blank=True, choices=[('HI', 'High'), ('ME', 'Medium'), ('LO', 'Low')], max_length=2, null=True)),
            ],
        ),
    ]
