# Generated by Django 4.2.13 on 2024-06-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='human_presence',
            field=models.CharField(blank=True, choices=[('M', 'Multiple'), ('S', 'Single'), ('-', 'None'), ('?', 'Unknown')], max_length=1, null=True),
        ),
    ]
